SELECT --COUNT_BIG( EKPO.EBELN ) AS 'TOTAL RECORDS'
	TOP (100)
	EKPO.EBELN
	,EKPO.MENGE
	,EKPO.MEINS
	,EKPO.BPRME
	,EKPO.NETWR
	,EKPO.BRTWR
	,EKPO.TXZ01
	,EKPO.NETPR
	,EKPO.PEINH
	,EKPO.MATNR 
	,EKKO.BEDAT
  FROM [FinanceDa].[dbo].[vtEkpo] AS EKPO
  INNER JOIN  [Source].[SapEcc].[vtEkko] as EKKO on EKPO.EBELN = EKKO.EBELN
  WHERE EKPO.[MATNR] = '000000000002099002'