SELECT 	
	KO.EBELN, 
	PO.EBELP, 
	KO.BSART, 
	KO.LIFNR, 
	VEND.NAME1, 
	KO.EKORG, 
	KO.EKGRP, 
	KO.BEDAT, 
	KO.BSTYP, 
	PO.WERKS, 
	PO.MATKL, 
	PO.NETWR, 
	PO.PSTYP, 
	PO.MTART, 
	PO.ELIKZ, 
	KO.ERNAM, 
	PO.MENGE, 
	PO.NETPR, 
	PO.MEINS, 
	KO.WAERS, 
	PO.EMATN,
	NETPR2 = (CASE
		WHEN (PO.MENGE <=0) THEN 0
		WHEN ((PO.MEINS = 'GAL') AND ((PO.NETWR / PO.MENGE) < 50)) THEN (PO.NETWR / PO.MENGE)
		WHEN (PO.MEINS = 'BBL') THEN (PO.NETWR / PO.MENGE) / 42
		ELSE (PO.NETWR / PO.MENGE) / 12275 * 41
		END
		)
FROM            
	Source.SapEcc.vtEkpo AS PO 
	INNER JOIN
		Source.SapEcc.vtEkko AS KO ON KO.EBELN = PO.EBELN INNER JOIN
        Source.SapEcc.vtLfa1 AS VEND ON VEND.LIFNR = KO.LIFNR
WHERE        
	(PO.WERKS = 'PKTN') 
	AND (KO.BSART = 'ZB') 
	AND (PO.MATNR = '000000000002099002')